POST http://localhost:8080/tasks
X-API-Key: supersecretkey
Content-Type: application/json

{"title":"Deniska","status":"todo"}

###

GET http://localhost:8080/tasks/2
X-API-Key: supersecretkey

###

PUT http://localhost:8080/tasks/1
X-API-Key: supersecretkey
Content-Type: application/json

{"title":"Updated Task","status":"done"}

###

DELETE http://localhost:8080/tasks/1
X-API-Key: supersecretkey